/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.dbs.java.mps.view;

import java.awt.Frame;

/**
 *
 * @author DBS
 */
public class PlaylistDialog extends javax.swing.JDialog {

    public PlaylistDialog(Frame owner, boolean modal) {
        super(owner, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoesCimaPnl = new javax.swing.JPanel();
        novaPlaylistBtn = new javax.swing.JButton();
        excluirPlaylistBtn = new javax.swing.JButton();
        executarBtn = new javax.swing.JButton();
        pararBtn = new javax.swing.JButton();
        playlistsPnl = new javax.swing.JScrollPane();
        playlistsTbl = new javax.swing.JTable();
        musicasPnl = new javax.swing.JScrollPane();
        musicasTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Playlist");

        botoesCimaPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botoesCimaPnl.setLayout(new java.awt.GridLayout(4, 0));

        novaPlaylistBtn.setText("Nova Playlist");
        botoesCimaPnl.add(novaPlaylistBtn);

        excluirPlaylistBtn.setText("ExcluirPlaylist");
        botoesCimaPnl.add(excluirPlaylistBtn);

        executarBtn.setText("Executar");
        botoesCimaPnl.add(executarBtn);

        pararBtn.setText("Parar");
        botoesCimaPnl.add(pararBtn);

        playlistsPnl.setBackground(new java.awt.Color(204, 255, 204));

        playlistsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        playlistsPnl.setViewportView(playlistsTbl);

        musicasTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        musicasPnl.setViewportView(musicasTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(musicasPnl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playlistsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botoesCimaPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playlistsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botoesCimaPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(musicasPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoesCimaPnl;
    private javax.swing.JButton excluirPlaylistBtn;
    private javax.swing.JButton executarBtn;
    private javax.swing.JScrollPane musicasPnl;
    private javax.swing.JTable musicasTbl;
    private javax.swing.JButton novaPlaylistBtn;
    private javax.swing.JButton pararBtn;
    private javax.swing.JScrollPane playlistsPnl;
    private javax.swing.JTable playlistsTbl;
    // End of variables declaration//GEN-END:variables
}
