/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.dbs.java.mps.view;

import br.com.dbs.java.mps.controller.PlaylistController;
import br.com.dbs.java.mps.model.Playlist;
import br.com.dbs.java.mps.view.table.MusicaTableModel;
import br.com.dbs.java.mps.view.table.PlaylistTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class PlaylistDialog extends javax.swing.JDialog {

    private PlaylistController controller = new PlaylistController(this);
    
    /**
     * Creates new form PlaylistDialog
     */
    public PlaylistDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoesPnl = new javax.swing.JPanel();
        novaPlaylistBtn = new javax.swing.JButton();
        excluirPlaylistBtn = new javax.swing.JButton();
        executarBtn = new javax.swing.JButton();
        pararBtn = new javax.swing.JButton();
        playlistsPnl = new javax.swing.JScrollPane();
        playlistTbl = new javax.swing.JTable();
        musicasPnl = new javax.swing.JScrollPane();
        musicasTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Playlist");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        botoesPnl.setLayout(new java.awt.GridLayout(4, 0));

        novaPlaylistBtn.setText("Nova Playlist");
        novaPlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaPlaylistBtnActionPerformed(evt);
            }
        });
        botoesPnl.add(novaPlaylistBtn);

        excluirPlaylistBtn.setText("Excluir Playlist");
        excluirPlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPlaylistBtnActionPerformed(evt);
            }
        });
        botoesPnl.add(excluirPlaylistBtn);

        executarBtn.setText("Executar");
        botoesPnl.add(executarBtn);

        pararBtn.setText("Parar");
        botoesPnl.add(pararBtn);

        playlistTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        playlistTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playlistTblMouseClicked(evt);
            }
        });
        playlistsPnl.setViewportView(playlistTbl);

        musicasTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        musicasPnl.setViewportView(musicasTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(musicasPnl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playlistsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botoesPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playlistsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botoesPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musicasPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void novaPlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaPlaylistBtnActionPerformed
        new PlaylistFormDialog(this, controller).setVisible(true);
    }//GEN-LAST:event_novaPlaylistBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        controller.carregaPlaylists();
    }//GEN-LAST:event_formWindowOpened

    private void playlistTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playlistTblMouseClicked
        if (evt.getClickCount() == 1)
            controller.carregaMusicasDaPlaylist(playlistTbl.getSelectedRow());
        
        if (evt.getClickCount() == 2)
            controller.carregaPlaylistNoForm();
    }//GEN-LAST:event_playlistTblMouseClicked

    private void excluirPlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPlaylistBtnActionPerformed
        controller.excluir(playlistTbl.getSelectedRow());
    }//GEN-LAST:event_excluirPlaylistBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoesPnl;
    private javax.swing.JButton excluirPlaylistBtn;
    private javax.swing.JButton executarBtn;
    private javax.swing.JScrollPane musicasPnl;
    private javax.swing.JTable musicasTbl;
    private javax.swing.JButton novaPlaylistBtn;
    private javax.swing.JButton pararBtn;
    private javax.swing.JTable playlistTbl;
    private javax.swing.JScrollPane playlistsPnl;
    // End of variables declaration//GEN-END:variables

    public void atualizaTabelaPlaylist(PlaylistTableModel playlistTableModel) {
        playlistTbl.setModel(playlistTableModel);
        playlistTbl.repaint();
    }

    public void atualizaTabelaMusicasDaPlaylist(MusicaTableModel musicaTableModel) {
        musicasTbl.setModel(musicaTableModel);
        musicasTbl.repaint();
    }

    public void mostraMensagem(String sucesso) {
        JOptionPane.showMessageDialog(this, sucesso);
    }
}
