/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.dbs.java.mps.view;

import br.com.dbs.java.mps.controller.PlaylistController;
import br.com.dbs.java.mps.view.table.MusicaTableModel;
import br.com.dbs.java.mps.view.table.PlaylistTableModel;
import java.awt.Frame;

/**
 *
 * @author DBS
 */
public class PlaylistDialog extends javax.swing.JDialog {

    private PlaylistController controller =
            new PlaylistController(this);
    
    public PlaylistDialog(Frame owner, boolean modal) {
        super(owner, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoesCimaPnl = new javax.swing.JPanel();
        novaPlaylistBtn = new javax.swing.JButton();
        excluirPlaylistBtn = new javax.swing.JButton();
        executarBtn = new javax.swing.JButton();
        pararBtn = new javax.swing.JButton();
        playlistsPnl = new javax.swing.JScrollPane();
        playlistsTbl = new javax.swing.JTable();
        musicasPnl = new javax.swing.JScrollPane();
        musicasTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Playlist");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        botoesCimaPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botoesCimaPnl.setLayout(new java.awt.GridLayout(4, 0));

        novaPlaylistBtn.setText("Nova Playlist");
        novaPlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaPlaylistBtnActionPerformed(evt);
            }
        });
        botoesCimaPnl.add(novaPlaylistBtn);

        excluirPlaylistBtn.setText("ExcluirPlaylist");
        botoesCimaPnl.add(excluirPlaylistBtn);

        executarBtn.setText("Executar");
        executarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executarBtnActionPerformed(evt);
            }
        });
        botoesCimaPnl.add(executarBtn);

        pararBtn.setText("Parar");
        pararBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararBtnActionPerformed(evt);
            }
        });
        botoesCimaPnl.add(pararBtn);

        playlistsPnl.setBackground(new java.awt.Color(204, 255, 204));

        playlistsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        playlistsTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playlistsTblMouseClicked(evt);
            }
        });
        playlistsPnl.setViewportView(playlistsTbl);

        musicasTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        musicasPnl.setViewportView(musicasTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(musicasPnl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playlistsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botoesCimaPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playlistsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botoesCimaPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(musicasPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        controller.preencheTabelaPlaylist();
    }//GEN-LAST:event_formWindowOpened

    private void playlistsTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playlistsTblMouseClicked
        
        if (evt.getClickCount() == 1) {
            controller.carregaMusicasDaPlaylistView(
                    playlistsTbl.getSelectedRow());
        }
        
        if (evt.getClickCount() == 2) {
            final PlaylistFormDialog form = new PlaylistFormDialog(this, controller);
            form.carregaPlaylistDaLinha(playlistsTbl.getSelectedRow());
            form.setVisible(true);
            
        }
        
    }//GEN-LAST:event_playlistsTblMouseClicked

    private void executarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executarBtnActionPerformed
        controller.executarPlaylist(playlistsTbl.getSelectedRow());
    }//GEN-LAST:event_executarBtnActionPerformed

    private void pararBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararBtnActionPerformed
        controller.pararPlaylist(playlistsTbl.getSelectedRow());
    }//GEN-LAST:event_pararBtnActionPerformed

    private void novaPlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaPlaylistBtnActionPerformed
        new PlaylistFormDialog(this, controller).setVisible(true);
    }//GEN-LAST:event_novaPlaylistBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoesCimaPnl;
    private javax.swing.JButton excluirPlaylistBtn;
    private javax.swing.JButton executarBtn;
    private javax.swing.JScrollPane musicasPnl;
    private javax.swing.JTable musicasTbl;
    private javax.swing.JButton novaPlaylistBtn;
    private javax.swing.JButton pararBtn;
    private javax.swing.JScrollPane playlistsPnl;
    private javax.swing.JTable playlistsTbl;
    // End of variables declaration//GEN-END:variables

    public void atualizaTabelaPlaylist(PlaylistTableModel playlistTableModel) {
        playlistsTbl.setModel(playlistTableModel);
        playlistsTbl.repaint();
    }

    public void atualizaTabelaMusicas(MusicaTableModel musicaTableModelView) {
        musicasTbl.setModel(musicaTableModelView);
        musicasTbl.repaint();
    }
}
