/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.dbs.java.mps.view;

import br.com.dbs.java.mps.controller.PlaylistController;
import br.com.dbs.java.mps.model.Musica;
import br.com.dbs.java.mps.model.Playlist;
import br.com.dbs.java.mps.view.table.MusicasPlaylistListModel;
import java.util.List;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author daniel
 */
public class PlaylistFormDialog extends javax.swing.JDialog {

    private PlaylistController controller;
    
    /**
     * Creates new form PlaylistFormDialog
     */
    public PlaylistFormDialog(JDialog parent, PlaylistController controller, Playlist playlist) {
        super(parent);
        this.controller = controller;
        this.controller.registraViewCadastro(this);
        this.controller.setPlaylist(playlist);
        initComponents();
    }

    PlaylistFormDialog(PlaylistDialog aThis, PlaylistController controller) {
        this(aThis, controller, new Playlist());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoesPnl = new javax.swing.JPanel();
        salvarBtn = new javax.swing.JButton();
        playlistFormPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomePlaylistTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        duracaoPlaylistTxt = new javax.swing.JTextField();
        musicasDisponivelPnl = new javax.swing.JPanel();
        musicasDisponiveisScrollPnl = new javax.swing.JScrollPane();
        musicasDisponiveisLst = new javax.swing.JList();
        musicasPlaylistPnl = new javax.swing.JPanel();
        musicasPlaylistScrollPnl = new javax.swing.JScrollPane();
        musicasPlaylistLst = new javax.swing.JList();
        botoesControlePnl = new javax.swing.JPanel();
        adicionarBtn = new javax.swing.JButton();
        removerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Playlist");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        botoesPnl.setBackground(new java.awt.Color(1, 83, 254));

        salvarBtn.setText("Salvar");
        salvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBtnActionPerformed(evt);
            }
        });
        botoesPnl.add(salvarBtn);

        playlistFormPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Playlist"));

        jLabel1.setText("Nome");

        jLabel2.setText("Duração");

        javax.swing.GroupLayout playlistFormPnlLayout = new javax.swing.GroupLayout(playlistFormPnl);
        playlistFormPnl.setLayout(playlistFormPnlLayout);
        playlistFormPnlLayout.setHorizontalGroup(
            playlistFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlistFormPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomePlaylistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(duracaoPlaylistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        playlistFormPnlLayout.setVerticalGroup(
            playlistFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlistFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(nomePlaylistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(duracaoPlaylistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        musicasDisponivelPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Músicas Disponíveis"));

        musicasDisponiveisScrollPnl.setViewportView(musicasDisponiveisLst);

        javax.swing.GroupLayout musicasDisponivelPnlLayout = new javax.swing.GroupLayout(musicasDisponivelPnl);
        musicasDisponivelPnl.setLayout(musicasDisponivelPnlLayout);
        musicasDisponivelPnlLayout.setHorizontalGroup(
            musicasDisponivelPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicasDisponivelPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(musicasDisponiveisScrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        musicasDisponivelPnlLayout.setVerticalGroup(
            musicasDisponivelPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(musicasDisponiveisScrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        musicasPlaylistPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Músicas da Playlist"));

        musicasPlaylistScrollPnl.setViewportView(musicasPlaylistLst);

        javax.swing.GroupLayout musicasPlaylistPnlLayout = new javax.swing.GroupLayout(musicasPlaylistPnl);
        musicasPlaylistPnl.setLayout(musicasPlaylistPnlLayout);
        musicasPlaylistPnlLayout.setHorizontalGroup(
            musicasPlaylistPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicasPlaylistPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(musicasPlaylistScrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        musicasPlaylistPnlLayout.setVerticalGroup(
            musicasPlaylistPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(musicasPlaylistScrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        botoesControlePnl.setLayout(new java.awt.GridLayout(10, 0));

        adicionarBtn.setText(">>");
        adicionarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarBtnActionPerformed(evt);
            }
        });
        botoesControlePnl.add(adicionarBtn);

        removerBtn.setText("<<");
        removerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBtnActionPerformed(evt);
            }
        });
        botoesControlePnl.add(removerBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botoesPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playlistFormPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(musicasDisponivelPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botoesControlePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(musicasPlaylistPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playlistFormPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(musicasDisponivelPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(musicasPlaylistPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoesControlePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botoesPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtnActionPerformed
        controller.salvar();
    }//GEN-LAST:event_salvarBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        controller.carregaListaMusicasDisponiveis();
        controller.preencheFormularioEdicao();
    }//GEN-LAST:event_formWindowOpened

    private void adicionarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarBtnActionPerformed
        controller.adicionarMusicaNaPlaylist(musicasDisponiveisLst.getSelectedValue());
    }//GEN-LAST:event_adicionarBtnActionPerformed

    private void removerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBtnActionPerformed
        controller.removerMusicaDaPlayList(musicasPlaylistLst.getSelectedValue());
    }//GEN-LAST:event_removerBtnActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarBtn;
    private javax.swing.JPanel botoesControlePnl;
    private javax.swing.JPanel botoesPnl;
    private javax.swing.JTextField duracaoPlaylistTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList musicasDisponiveisLst;
    private javax.swing.JScrollPane musicasDisponiveisScrollPnl;
    private javax.swing.JPanel musicasDisponivelPnl;
    private javax.swing.JList musicasPlaylistLst;
    private javax.swing.JPanel musicasPlaylistPnl;
    private javax.swing.JScrollPane musicasPlaylistScrollPnl;
    private javax.swing.JTextField nomePlaylistTxt;
    private javax.swing.JPanel playlistFormPnl;
    private javax.swing.JButton removerBtn;
    private javax.swing.JButton salvarBtn;
    // End of variables declaration//GEN-END:variables

    public String getNome() {
        return nomePlaylistTxt.getText();
    }

    public void mostraMensagem(String sucesso) {
        JOptionPane.showMessageDialog(this, sucesso);
    }

    public void atualizaListaMusicasDisponiveis(ListModel model) {
        musicasDisponiveisLst.setModel(model);
        musicasDisponiveisLst.repaint();
    }

    public void atualizaListaMusicasPlaylist(MusicasPlaylistListModel listModelMusicasPlaylist) {
        musicasPlaylistLst.setModel(listModelMusicasPlaylist);
        musicasPlaylistLst.repaint();
    }

    public void fecha() {
        dispose();
    }

    public void setDuracao(String duracaoTotal) {
        duracaoPlaylistTxt.setText(duracaoTotal);
    }

    public void setNome(String nome) {
        nomePlaylistTxt.setText(nome);
    }

    public void limpaCampos() {
        setNome(null);
        setDuracao(null);
        atualizaListaMusicasPlaylist(null);
    }
}
